### ISSUE TITLE
run_inference的时候遇到一个有趣的现象

### ISSUE THREAD

**Issue by deepmeng** [overfitover/pixor_ovo#7]
单独制定某一个要检测的图片编号，如 image_id = 25, 然后加载，检测，结果显示正常。

当我把要预测的多个图片编号放到一个列表中，例如 image_id = [1, 2, 3, .....25]，然后连续进行(加载指定数据，检测， 保存检测结果)的时候，输出的结果乱七八糟。。。我又试了一下列表中只放一个编号，例如image_id=[25]，输出结果又正常了。

简直薛定谔的pixor啊。。。T_T...
@overfitover @xiaokuiyang 有遇到这个问题吗

**Comment by overfitover** [comment]
@deepmeng 
看代码啊，实际上我取消了多张图片的检测。如果你想对多张图片进行检测的话可以稍微修改一下。
''' # for image_id in image_ids: '''
把这句注释取消，然后调整一下就好了。
你怎么找到的彩色点云？

**Comment by deepmeng** [comment]
谢谢答复，你没明白我的意思。我给你放几张图片看看。

单独检测的时候：
image_ids=[25]
![image](https://user-images.githubusercontent.com/8176780/57230572-38d74180-704b-11e9-8722-2455c1009595.png)

连续检测的时候：
image_ids=[7, 8, 9, 10, 25]
![image](https://user-images.githubusercontent.com/8176780/57230662-7340de80-704b-11e9-8f10-eccf0a08e9ff.png)

![image](https://user-images.githubusercontent.com/8176780/57230669-789e2900-704b-11e9-9312-4ae8024ca045.png)
![image](https://user-images.githubusercontent.com/8176780/57230682-7fc53700-704b-11e9-8730-eb90b2bd8a3b.png)

![image](https://user-images.githubusercontent.com/8176780/57230692-8784db80-704b-11e9-812b-e978c9cc855c.png)

**Comment by overfitover** [comment]
@deepmeng 
很有意思，我不知道你修改了什么，我这边没有问题呢。你是做了什么修改吗？你可以试试重新拷贝一份run_inference.py试试。或者你给我你的代码，我看看。

**Comment by deepmeng** [comment]
跪谢大佬，你邮箱多少，我发你源文件

**Comment by overfitover** [comment]
m18603760829@163.com
你可以直接在这里回复的。代码不多

**Comment by deepmeng** [comment]
If anyone meets the same problem, try using "for idx, (pc_feature, label_map) in enumerate(loader):" instead of " for image_id in image_ids:" to access the dataset.
